### ISSUE TITLE
How to add a logo in the center of the QR code

### ISSUE THREAD

**Issue by Sen-Aldelo** [dagronf/QRCode#1]
This project is really awesome, swift oc swiftUI all support, thank you. 
I would like to ask a question, how to add a logo in the center of the QR code？

**Comment by dagronf** [comment]
Hey mate!

The library current doesn't support adding an image to the generated image at this point.  However, you should be able to add the image relatively easily after it is generated by using UIKit drawing code. For an example, check this out

https://stackoverflow.com/questions/29203663/how-can-i-make-a-composite-image-consisting-of-two-images-in-swift

Just remember to make sure that the overlay image isn't too big or else it will stop the qr code being recognised.  The higher you make the error correction for the code the larger you can make the image. Also keep the image away from the 'eyes' in the code as they are used to orient the reader.

I'd like to add image support to the library but there are a lot of 'configuration' options when adding the image (size, position, masking etc.) and I haven't had the time to think through them all.

**Comment by noblakit01** [comment]
Hi @dagronf, do we have a properties to exclusive center path of QR code so that when add logo it won't affects the recognition.

**Comment by dagronf** [comment]
No, the library doesn’t have that capability yet.

The allowable size of the logo will be dependent on a number of factors, including the size of the text content and the error correction level. The logo also doesn’t always have to be square/round and it doesn’t have to be in the middle of the QR code - and as I haven’t needed a add a logo yet I haven’t thought hard about a (reliable) mechanism of adding it into to library.

You can add one yourself afterward (eg if you are using SwiftUI you can just overlay one using a ZStack.) but you’ll have to determine the size for yourself at this point.

hope this helps!

**Comment by dagronf** [comment]
@noblakit01 Additionally, you could fork this library and add the ability to add a logo yourself - and then submit a pull request and I’ll merge it in 😊

**Comment by ArtRoman** [comment]
You can just add an Image above QR-code. For example, I'm using `ZStack(alignment: .center)` with both QRCodeUI and my resized icon with cornerRadius inside.

**Comment by dagronf** [comment]
Check v11.0.0 which now has the ability to add an image to the generated qr code
