### ISSUE TITLE
Wrong getting image from QRCodePixelShapeFactory.shared.image

### ISSUE THREAD

**Issue by nikolay303** [dagronf/QRCode#13]
Hello, @dagronf!
I use your library and I want to get all image of PixelShape, but it's not working for roundedRect, horizontal and vertical types. For this types I get the same image like as default.
How can I get right images for this types?
Also I can't apply this types for QR code.

**Comment by dagronf** [comment]
When using the factory to create the generator, you need to pass the settings for the generator.  In the case of the roundedRect and the other types you've mentioned, the corner radius defaults to 0.0 (which means that the corners are not rounded) - you need to set the value in the creator function like so :-

```swift
let ps = QRCodePixelShapeFactory.shared.named(
   "roundedRect",
   settings: [QRCode.SettingsKey.cornerRadiusFraction : 0.7]
)!

let im = QRCodePixelShapeFactory.shared.image(pixelShape: ps, dimension: 300, foregroundColor: CGColor.black)
Swift.print(im)
```

**Comment by nikolay303** [comment]
Thank you, @dagronf!
It's work well.
