### ISSUE TITLE
Can't add with package manager

### ISSUE THREAD

**Issue by TillMoss** [dagronf/QRCode#14]
I get "package Resolution failed"

**Comment by dagronf** [comment]
What have you tried? How are you trying to import it? Via Xcode or as part of another package? What version of Xcode are you using?

**Comment by TillMoss** [comment]
I'm trying to use "add Package". The version of Xcode is the last.

<img width="1065" alt="Screenshot 2023-04-04 alle 12 22 56" src="https://user-images.githubusercontent.com/2966339/229763215-2c1c7f3e-1075-43ae-9c4a-75ffa2894401.png">

**Comment by TillMoss** [comment]
Sorry but I don't know why now it works

**Comment by dagronf** [comment]
Good news!
