### ISSUE TITLE
Cannot find 'NSPoint' in scope

### ISSUE THREAD

**Issue by brunomunizaf** [dagronf/QRCode#15]
Hello! 

I'm trying to use this repo as a swift package on my iOS 16 app but unfort. I'm facing this compile issue (72 occurrences) at `QRCodePupilShapeShield.swift`

In my `Package.swift` dependencies:
```swift
.package(url: "https://github.com/dagronf/qrcode.git", from: "13.5.1")
```
In my `Package.swift` target dependencies:
```
.product(name: "QRCode", package: "QRCode")
```

**Comment by dagronf** [comment]
What is the compile error?

**Comment by dagronf** [comment]
Okay grab 13.5.2 (just update your package). Left in some macOS specific types.

**Comment by brunomunizaf** [comment]
Sorry, i left the compile error at the title of the issue. Yeah, works great now
Thank you very much for your quick response

**Comment by dagronf** [comment]
Apologies for the bug!
