### ISSUE TITLE
CocoaPods Podspec file support. 

### ISSUE THREAD

**Issue by sench93** [dagronf/QRCode#16]
Project is not added to Cocoapods. Yes it has a valid podspec file which we can use in our projects. But if we are developing a library we can't use it in our own .podspec files because Cocoapods doesn't allow to use  tags in dependency declarations. I suggest to add it to Cocoapods. 

Of course I can do it myself and don't tell a thing or bother you, but it won't be fair cause it will permanently go to Cocoapods under my name. I did upload to Cocoapods for my own using. But will remove it at the same moment you add it to Cocoapods. For your information i added tag 13.9.0 and it passed lint validation. So it will be easier to do for you. 

Here are steps to publish it to Cocoapods. 

1. Register your trunk in Cocoapods. Remove <> characters. U used it just for placeholders. But keep '' characters. You should receive an email with link. Click the link and wait it to finish. As their website is super unresponsive it can take few minutes. 

`pod trunk register <your@email.com> '<your Name>' --description='<your description>'`

2. Edit version line in your podscep file to match the latest TAG in your git repository. Or the one you want to publish. 

`s.version                    = '13.9.0'`

3. Change the name in your posdpec file. QRCode name is used in Cocoapods so you will need a unique name. 

`s.name                       = 'QRCode_SOMETHING_UNIQUE'`

4. Change the file name in your podspec file to match the s.name parameter in podspec file. 
5. Run following command. If the output is **<filename> passed validation** then we are good to go. If now check what errors you have. 

`pod lib lint --no-clean`

6. On final step run following command. You will receive an email if everything is correct. Sometimes command will give an HTML error even if it's success. Just check the email. If email is there then you are good. 

`pod trunk push <filename>.podspec`

After this step developers can be able to access your library via this command. 

`pod 'QRCode_SOMETHING_UNIQUE', '~> 13.9.0'`

**Comment by dagronf** [comment]
Unfortunately, there is a bug with Cocoapods and Xcode 14.3 which hasn't been resolved yet.

See [Cocoapod reported bug](https://github.com/CocoaPods/CocoaPods/issues/11839)

The third party qr code generator library targets macOS 10.10 (even though QRCode targets 10.11), which breaks the cocoapods lint process.  I've contacted the thrid party library owner but have heard nothing back.

**Comment by dagronf** [comment]
Okay so I got this to work by pushing the QRCode library to trunk using Xcode 14.2.

The library name is 'DSF_QRCode' (as there is already a QRCode).

**Comment by dagronf** [comment]
v16.0 should be fine with
