### ISSUE TITLE
No such module 'QRCodeGenerator'

### ISSUE THREAD

**Issue by sppzglou** [dagronf/QRCode#17]
I can not import the library with Swift package manager.
When import the qrCode lib I received this error.
<img width="1438" alt="Στιγμιότυπο οθόνης 2023-04-22, 3 20 56 μμ" src="https://user-images.githubusercontent.com/81743352/233784540-862c12dc-0a1d-423f-86d7-ed3ef8ed9e0d.png">

**Comment by dagronf** [comment]
I just tested this using a completely new iOS project without issue, Xcode 14.3 (14E222b).  Given that `QRCodeGenerator` is an external dependency it's possible that Xcode didn't download it successfully? Can you check that the package dependencies aren't showing any errors?

<img width="373" alt="image" src="https://user-images.githubusercontent.com/2636615/233886265-720202c0-c91e-4804-8202-58075c545128.png">

Which version of Xcode are you using? Have you tried quitting xcode and re-opening the project? Which OS are you targetting (iOS, macOS, tvOS, watchOS?).

**Comment by sppzglou** [comment]
I have tried again and again in a new project. 
Xcode Version 14.3 (14E222b)
iOS 16.4

https://user-images.githubusercontent.com/81743352/233922173-adc4bc6f-9dd6-42dc-9c93-cdc02e115bf8.mov

**Comment by dagronf** [comment]
Unfortunately the video is not showing. I can hear the audio, but no video is present.

**Comment by dagronf** [comment]
Did the package dependencies resolve correctly?

**Comment by sppzglou** [comment]
this is mine
[qrcodetest.zip](https://github.com/dagronf/QRCode/files/11308324/qrcodetest.zip)

**Comment by dagronf** [comment]
Okay I got yours to compile.  You seem to have added _all_ library types to your project (QRCode, QRCodeDynamic, QRCodeStatic) and Xcode is getting very confused.

You only ever need to add a single one (likely just `QRCode`) to your project.  The other two are for projects that need to force a library type (a dynamic library or a static library). You can basically ignore them.

To fix the issue in  your project, go to the `general` tab in the project settings, look for 'Frameworks, Libraries, and Embedded Content'.  Remove all but `QRCode` from the list.

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/2636615/233949317-77f16046-01a3-4478-ab14-6048b4490fb7.png">

Now you should be able to compile and run correctly.

**Comment by dagronf** [comment]
When creating your project, you only need to select a single package project to add it to your project.

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/2636615/233950041-8a4161d8-179a-41f5-93a6-8f3cb678f0cb.png">

**Comment by sppzglou** [comment]
Yeah!! that's works! thank u very much <3

**Comment by dagronf** [comment]
My pleasure mate.  Glad I could help!
