### ISSUE TITLE
Circle QR

### ISSUE THREAD

**Issue by sppzglou** [dagronf/QRCode#18]
Is it possible to clip the qr code on a circle?

<img width="1028" alt="Στιγμιότυπο οθόνης 2023-04-19, 1 19 38 μμ" src="https://github.com/alexzhirkevich/custom-qr-generator/blob/main/screenshots/tiktok.png?raw=true">

**Comment by dagronf** [comment]
This is an interesting one as technically the QR code in your example isn't clipped at all -- they've extended the 'dots' around the QR code to fill a circular space. 

![image](https://user-images.githubusercontent.com/2636615/234141376-8644b940-83f1-4c41-9000-7152a07a81f3.png)

My guess is that they've just added a random dot pattern outside of their qr code. If you use a QR code capture program you'll see that it captures the _actual_ qr code embedded within the circle of random dots.

![image](https://user-images.githubusercontent.com/2636615/234140769-22192986-ef63-4f5f-8264-37dc47f8448e.png)

The library currently has no way of extending the QR code's 'dots' outside its bounds.
