### ISSUE TITLE
SVG output creating unusable images when using shapes other than defaults

### ISSUE THREAD

**Issue by keremerkan** [dagronf/QRCode#19]
Hi Darren,

Just discovered your project and it is incredible, thank you for such an awesome library. However I have encountered a problem with SVG generation. With shapes other than the default squares, SVG output creates unusable images.

I tried it on both my project and an app I found on the App Store, that uses your library. Attached are 2 images for the same QR Code. The SVG is unusable. PNG has no problems. I also tested PDF, and it does not have any problems.

Is this a known issue so we should avoid SVG for designs other than default, or is this a bug?

Best regards.

![Code](https://github.com/dagronf/QRCode/assets/1952491/33b4f045-28e5-4086-b90f-e898d53f11ea)
![Code](https://github.com/dagronf/QRCode/assets/1952491/b76cf2eb-3c63-46c0-80ba-a9c6d8d05303)

**Comment by dagronf** [comment]
Hey mate, sorry to hear you're having issues.

I can see the same issues when trying to open your svg on my machine here. Very odd!

I just tried making the same style of QR code that you're showing and exported it to SVG using this code...

```swift
func testIssue17ExportSVGIssue() throws {
   let d = QRCode.Document(utf8String: "This is a test")
   d.design.shape.eye = QRCode.EyeShape.RoundedOuter()
   d.design.shape.onPixels = QRCode.PixelShape.Circle()

   let str = d.svg(dimension: 600)
   try str.write(
      to: URL(fileURLWithPath: "/tmp/qrcode.svg"),
      atomically: true,
      encoding: .utf8
   )
}
```

which generated this file :-

![qrcode](https://github.com/dagronf/QRCode/assets/2636615/9dae18e2-d7ff-4b23-8289-cdf9749f7d07)

Interestingly, I can view this file correctly in Finder (quicklook), Firefox, Inkscape, Safari and Sketch... these are the apps that I was using to test SVG export.

Can you tell me the settings you're using to generate the QR Code? What pixel style, what eye style?  Even better, can you share your code that you're using to create the qr code?

**Comment by dagronf** [comment]
Here's an exact replica of your QR Code (down to the pixels) generated using the current version of the library...

![qrcode19](https://github.com/dagronf/QRCode/assets/2636615/5c0febd5-0963-44b5-84db-152e9eb3112d)

It's very odd. I'm wondering whether there's some combination of settings which is triggering the issue

**Comment by dagronf** [comment]
Ah! Would you possibly be located in a country that uses ',' as the decimal separator? 

Because I believe thats the issue with the SVG export. SVG expects '.' as the decimal separator - and I'm using a NumberFormatter to format the float values in the SVG export. The NumberSeparator always uses the Locale to determine the decimal separator, thus it uses ','

Give me a moment...

**Comment by keremerkan** [comment]
Hi Darren,

Yes, that's the exact problem. I just came here to write that to say that I found the issue and you were a step ahead of me. My region uses "," instead of "." and the svg was becoming corrupt because of that. I had changed the region to US to see that the issue was fixed not even touching my code.

**Comment by dagronf** [comment]
Brilliant mate.  Thank you for reporting it - so glad I can help out.

Apologies for the inconvenience.

Oh and btw. which program in the App Store is using the library? Would be interested in having a look...

**Comment by keremerkan** [comment]
The app I used is called QR Pop. The developer seems to utilize your library very well.

BTW, I am adding your library to my app Qrafter which is probably the oldest QR Code app on App Store that still gets regular updates. I just rewrote it using Swift, and your library was the last piece to make it perfect. :) Thank you very much again for creating such an awesome tool.

**Comment by dagronf** [comment]
Always great to hear that. Thank you so much!
