### ISSUE TITLE
Enhancement suggestion: Quiet zone width option

### ISSUE THREAD

**Issue by keremerkan** [dagronf/QRCode#21]
I am sorry for bombarding the project with suggestions, but this is also good to have (though I don't know if it can be easily implemented)

Would it be possible to add a variable quiet zone width (in QR Code blocks)? Currently the width seems to be fixed as one block and I could not find a way to change that. In QR Code designs, people sometimes use wider quiet zones and it makes sense to present the option to them directly in the generator.

**Comment by dagronf** [comment]
Hey mate - if you're interested I've added in support for a quiet zone -- you can set the size of the quiet zone on the design object in the document like this

```swift
doc.design.additionalQuietZonePixels = 5
```

![quiet-space-5](https://github.com/dagronf/QRCode/assets/2636615/0d0dda24-dab1-40b0-a748-c4c20625b287)

I've updated the version to the next major version (14.0.1) as there has been some tweaking around in the generation code so there's always a possibility that I've missed something.  One of the tests in the XCTests (QRCodeDocGenerator.testGeneration) generates a styles.md document which generates a huge combination of QR codes and it seems generating all the existing codes correctly (plus it now has a lot more examples in it).

I've also added in an optional background corner radius.

The README.md has been updated with the new details.

If you're able it would be awesome if you could play around with it.  Especially the SVG generator with quiet zone

**Comment by dagronf** [comment]
![36CCEC5D-10D0-4204-B5FA-76E6242A4399-50504-00001688E979E3C6](https://github.com/dagronf/QRCode/assets/2636615/fac8d1b1-6a6d-4eef-89bd-a71ac79021b3)

**Comment by dagronf** [comment]
![15961CC5-D165-4FAE-A106-85901333384F-50504-000016C15840D694](https://github.com/dagronf/QRCode/assets/2636615/6a9854e8-d399-4f96-8f18-0e2425a31780)

**Comment by keremerkan** [comment]
This is awesome! Thank you for such a quick implementation. I’ll definitely test it. Just to be sure, to have a quiet zone of 2 pixels, I need to set additionalQuietZonePixels = 1, right?

Background corner radius makes a lot of sense with a wider quiet zone in some designs. Very clever!

**Comment by dagronf** [comment]
> Just to be sure, to have a quiet zone of 2 pixels, I need to set additionalQuietZonePixels = 1, right?

Yup that's correct

**Comment by keremerkan** [comment]
Well, my last enhancement question is how can I buy you a beer :)
