### ISSUE TITLE
Example question

### ISSUE THREAD

**Issue by NickAtGit** [dagronf/QRCode#22]
Hey, great project. Really cool!

I was wondering how you made this here? 

https://github.com/dagronf/QRCode/blob/main/Art/qrcode-off-pixels.png

Can you provide some sample code for this please?

Thanks!

**Comment by dagronf** [comment]
[Yup](https://github.com/dagronf/QRCode/blob/main/Examples/red-b/red-b.md)

**Comment by dagronf** [comment]
No, there is no automatic detection in this library.

**Comment by NickAtGit** [comment]
Forget what I said. I think I had a misunderstanding in my head. Thanks again!
