### ISSUE TITLE
New shiny pixel shape renders off center

### ISSUE THREAD

**Issue by keremerkan** [dagronf/QRCode#23]
The new shiny pixel seems to render off center to both right and down. This results in a slightly misaligned QR Code.

**Comment by dagronf** [comment]
@keremerkan hey mate - can you check the 14.2.1 build and check that the fix resolves your issue?

**Comment by keremerkan** [comment]
Yes, 14.2.2 seems to resolve it on my side. :)

**Comment by dagronf** [comment]
Brilliant!
