### ISSUE TITLE
Adding a logo template inset after creating a template seems not to affect created mask size

### ISSUE THREAD

**Issue by keremerkan** [dagronf/QRCode#24]
I don't know if this is the intended mechanism but here it goes :)

If I don't want to use a predefined mask in my logo template and rely on the transparency of the image, I presume I should directly add the image to the template:
```
doc.logoTemplate = QRCode.LogoTemplate(image: image)
```
This lets QRCode library to generate a mask for the template. But the resulting logo image is way too big:

![IMG_0085](https://github.com/dagronf/QRCode/assets/1952491/79921f85-4da8-4d5f-8399-8f54c39fd63b)

Then I inset the image:
```
doc.logoTemplate?.inset = 500.0
```
**Enhancement suggestion:** Here I believe <code>inset</code> should be a relative size inside the QR Code, similar to the shape <code>insetFraction</code> variable for pixel shapes. That way, we could write something like:
```
doc.logoTemplate?.insetFraction = 0.25
```
And the logo would get reduced to the necessary percentage size regardless of the <code>CGImage</code> size. PS: This should be done ignoring <code>additionalQuietZonePixels</code> value so that the logo size does not change with any additional quiet zone width.

**BUG:** Now here is the bug (or unexpected behavior). When I inset the image with the command above, The image itself gets reduced in size, but the mask stays the same. Please see the resulting image:

![IMG_0084](https://github.com/dagronf/QRCode/assets/1952491/96196e41-ffd9-4582-b172-16bf56bc4213)

You can see that the pixels are masked with the original image size, while the image itself is smaller. Is this expected or am I again missing some configuration?

Thanks!

**Comment by dagronf** [comment]
I'll answer this is two parts.

**Part 1**

`doc.logoTemplate = QRCode.LogoTemplate(image: image)`

This method of masking treats the image as the same size as the resulting QR code. Looking at [the documentation](https://github.com/dagronf/QRCode#logo-only).  The transparent part of the image lets the qrcode components through, and the non-transparent parts show the image.

If your cat/heart image fill the entire image, then the first image you present is correct according to the interfaces.

I'm guessing what you're looking for is something like this :-
![cat-heart](https://github.com/dagronf/QRCode/assets/2636615/b261a2a9-a230-4d75-a3b7-c8a106b58cad)

Note that the image positions the image in the lower right with transparent pixels.

**Comment by dagronf** [comment]
I'll need some time for part 2...

**Comment by keremerkan** [comment]
I understand that the first image is correct. But after insetting the image, shouldn't it also inset the mask? I believe there may be a bug there.

**Comment by dagronf** [comment]
@keremerkan v14.4.0 has just been pushed up with an additional parameter to the LogoTemplate initializer (`masksQRCodePixels`) which turns on/off the qr pixel masking

**Comment by keremerkan** [comment]
@dagronf thanks! Just tested it and it works perfectly.
