### ISSUE TITLE
How to not import QRCode reader

### ISSUE THREAD

**Issue by spaquet** [dagronf/QRCode#25]
Is there a way to only import the QR code generation part of the library. That would avoid having to fill the NSCameraUsageDescription in the Info.plist when uploading an app to TestFlight or the AppStore.

**Comment by dagronf** [comment]
That's a great idea. I hadn't thought about that downside of including video detection in the core library.

I'll pull the video detector out into its own library, which will allow you to use QRCode without the Camera Usage requirement.

**Comment by dagronf** [comment]
Hey @spaquet I've just pushed up v15.0.0 which has the video detection stuff pulled out into a separate target (QRCodeDetector) so you should be able to push a version of your app without NSCameraUsageDescription.

Can you update your app with the new version and see if it fixes your issue?

**Comment by dagronf** [comment]
Closing. Assuming issue is fixed due to lack of response.

**Comment by spaquet** [comment]
Hey @dagronf I will test later after the 4th. But thanks for updating the library so quickly. I really enjoy using it in the project I'm working on.

**Comment by spaquet** [comment]
Once the app hits the App Store I'll let you know ;-)
