### ISSUE TITLE
Runtime crash

### ISSUE THREAD

**Issue by ltns35** [dagronf/QRCode#31]
Hi,

I'm having a runtime crash using the example code for SwiftUI. I'm trying it on an iPhone 14 Pro and iOS 17.1.1

<img width="1018" alt="QRCode-CRASH" src="https://github.com/dagronf/QRCode/assets/16757217/370e895d-12d7-4923-92a1-680205471ad1">

**Comment by dagronf** [comment]
Hi @ltns35, sorry you're having issues.

There's not enough information in your bug for me to begin to track down the issue.  Can you please tell me

* Which demo app in the project you were trying to run?
* Is it running on the simulator or on real hardware?
* Is it possible to get a crash report?

If it is not one of the example apps,

* Which example code?
* Is it possible to send me the code you are using to display the QRCode?  It would appear that that _something_ is being deallocated, but without more information on _how_ you are using QRCode its going to be very difficult for me to track it down. Doesn't have to be an entire project, but maybe (as it's SwiftUI) just the View definition?
* Even better, is it possible to send me a basic sample project that reproduces the crash you're seeing?

Cheers -- Darren.

**Comment by ltns35** [comment]
Hi,

I used this code, but other codes I found on the README doesn't work either. It's just a the default SwiftUI app and I'm using a real device.
```swift
QRCodeViewUI(content: "This is a test",
                           foregroundColor: CGColor(srgbRed: 1, green: 0.8, blue: 0.6, alpha: 1.0),
                           backgroundColor: CGColor(srgbRed: 0.2, green: 0.2, blue: 0.8, alpha: 1.0),
                           pixelStyle: QRCode.PixelShape.RoundedPath(cornerRadiusFraction: 0.7, hasInnerCorners: true),
                            eyeStyle: QRCode.EyeShape.RoundedRect())
```

**Comment by dagronf** [comment]
I've just tested using a brand new SwiftUI project in Xcode 15, using my iPhone 12 Pro max (unfortunately I don't have a hardware iPhone 14 to test against) and didn't see the same issue. I'm wondering whether there's something different in your  project settings that is causing the issue

Can you check in the settings of your project, that in the "Frameworks, Libraries and Embedded Content" section that there is only a single "QRCode" entry? Like this :-

<img width="925" alt="Screenshot 2023-11-17 at 7 41 44 am" src="https://github.com/dagronf/QRCode/assets/2636615/681633dc-ce24-44c7-9c8c-caaf390e3fb9">

I've attached my created project - can you try running it on your hardware?

**Comment by dagronf** [comment]
[bug-test.zip](https://github.com/dagronf/QRCode/files/13383195/bug-test.zip)

**Comment by ltns35** [comment]
I've tried your project and works without any crashing. The problem I think is related to my project configuration because I'm using Tuist to link the library.

I will investigate the problem and I found the root cause I will share it in this thread.

Thanks.

**Comment by sjackk** [comment]
Greetings, @ltns35 

I encountered the same problem and found a solution: the fact is that it is necessary to add such value **-ObjC** to the key OTHER_LDFLAGS (**Other Linker Flags**) in the **Project->Build Settings** so that the selector _drawWithCtx_ becomes visible in runtime. 

Without this flag, the linker may skip loading categories from static libraries, which can lead to runtime exceptions if your app expects those categories to be available.

With Tuist, you can specify this in your **Project.swift**

    `settings: Settings(`
        `base: [`
            `"OTHER_LDFLAGS": "-ObjC"`
        `],`
        `...`
    `)`

I hope it helps you.

Best wishes,
sjackk

**Comment by ltns35** [comment]
Thanks you so much, your solution works perfectly.

**Comment by dagronf** [comment]
Note I've added your solution to the README.md at the top of the project.  Thanks for your input!
