### ISSUE TITLE
building out to device

### ISSUE THREAD

**Issue by omendez11** [dagronf/QRCode#33]
Hello,   so I’m getting a "no file error for QRCodeDynamic. framework" in the DerivedData folder when I build the app to my device, it builds fine using the simulator..  Packages are installed fine.

Also, It builds fine to my device using your repository file.

Any ideas? 

Thanks,

**Comment by dagronf** [comment]
Are you sure your project is copying (embedding) the QRCodeDynamic.framework into your frameworks folder of your app?

<img width="889" alt="image" src="https://github.com/dagronf/QRCode/assets/2636615/f3841f27-ccee-40cf-9fef-ee7ca30b31ec">

**Comment by omendez11** [comment]
Hi @dagronf , that worked (:   Apparently it wasn't embedded when the packages was installed.  hmm.  I guess it's a manual process, unless my project was a one off that didn't do it.    btw, awesome job on this app you built..  Thank you!

**Comment by dagronf** [comment]
Hi @omendez11 , glad to hear that fixed your issue.  Xcode can be a little scatterbrained at times!  I've bumped into a similar issue on another project where I was _sure_ I'd marked the embed framework to copy but for some reason Xcode 'forgot' to add the stage.

Many thanks mate.  Have a great weekend!
