### ISSUE TITLE
If a QRCode has a non-square dimension _and_ a logotemplate, the logo draws out of location

### ISSUE THREAD

**Issue by dagronf** [dagronf/QRCode#34]
Reproduce: Build QRCodeView Demo > QRCodeView iOS Demo > Mac Catalyst and scale the window.

When you scale the window, the logo template image goes out of place.  The renderer is not taking into account the QRCode offset along the longer axis.

**Comment by fontalland** [comment]
I'm just testing the library in an iPad and I'm getting the same. The mask position is great but the image goes completely out of place.

**Comment by dagronf** [comment]
Hey @fontalland, I've just pushed up a new tag (19.3.0) which should resolve this issue.

Can i ask you to check out this new version and see if it fixes the issues you've seen?

Many thanks.

**Comment by fontalland** [comment]
> Hey @fontalland, I've just pushed up a new tag (19.3.2) which should resolve this issue.
> 
> Can i ask you to check out this new version and see if it fixes the issues you've seen?
> 
> Many thanks.

Sorry for taking too long for answering. Yes, it works better now. Thanks for the quick fix. : )

Great Great lib by the way!

**Comment by dagronf** [comment]
@fontalland Great news mate. And thank you!
