### ISSUE TITLE
Are there any version that support for iOS 12.0?

### ISSUE THREAD

**Issue by minhDTNHust** [dagronf/QRCode#35]

**Comment by dagronf** [comment]
@minhDTNHust no there isn't unfortunately. 

Technically there's nothing stopping it, just need to write some shims for some missing CGColor initializers if you're prepared to fork the codebase.

**Comment by minhDTNHust** [comment]
Thanks you for your support very much. I've done this!

**Comment by dagronf** [comment]
Hey mate - v18.0.0 now supports iOS 11 as a minimum target.

**Comment by minhDTNHust** [comment]
Yes I love it. Thanks you!
