### ISSUE TITLE
Missing architecture

### ISSUE THREAD

**Issue by VityaSchel** [dagronf/QRCode#38]
Hello! I'm getting this error. I'm not xcode developer, so I have no idea how to fix these.

<img width="544" alt="image" src="https://github.com/dagronf/QRCode/assets/59040542/be3e60e6-bc1c-4043-b093-3416ee163002">

Can you please help? I have set "build active architecture only" to No everywhere

**Comment by VityaSchel** [comment]
I tried switching to apple silicon but got this error
<img width="547" alt="image" src="https://github.com/dagronf/QRCode/assets/59040542/c84881d2-99e7-4a2a-95dc-2d72af27713f">

**Comment by VityaSchel** [comment]
i have no idea how I fixed this, but the steps were the following: 1. uninstall from SPM (swift package manager) 2. install via cocoapods 3. go to Pods app in workspace and set "build only active architecture" to no on every target in menu 4. switch destination to apple silicon

**Comment by dagronf** [comment]
It appears to be a [known concern](https://aptabase.com/blog/how-to-fix-swift-package-missing-architecture) [(archived link)](https://web.archive.org/web/20240317221542/https://aptabase.com/blog/how-to-fix-swift-package-missing-architecture)

Given that QRCode is built from source, the issue must be within the project that you're adding it to (which is what you've already found). Can you follow the steps outlined in the link I've provided and see if it solves your issue?

**Comment by dagronf** [comment]
Closing due to lack of feedback
