### ISSUE TITLE
Build time Error in QRCode+Document.swift and  QRCode+SVG.swift file...

### ISSUE THREAD

**Issue by nmLearner** [dagronf/QRCode#4]
"Static property 'black' is internal and cannot be referenced from a default argument value" while compiling the code. Xcode version - 13.4.1

**Comment by nmLearner** [comment]
Added 8.1.3, but now there is an error "No such module 'QRCodeGenerator'", I think this package is not properly integrated.

**Comment by dagronf** [comment]
I just downloaded the package as a ZIP file and opened and ran the demo apps and wasn't able to generate the issue you're seeing/

I also tried creating a new project and adding QRCode as a dependency and still can't generate the issue.

Can you give me some more info as to what you're doing? Or attach a zip file containing the project thats failing?

**Comment by dagronf** [comment]
Maybe reset the package cache by doing a 'Reset package caches' (Xcode -> File Menu)?

**Comment by nmLearner** [comment]
I was adding all the options asked while adding package, Issue was resolved when only added 'QR code',...
