### ISSUE TITLE
Tell me the structure of the qrtemplate.json file

### ISSUE THREAD

**Issue by TakNePoidet** [dagronf/QRCode#44]
This one doesn't work

```json
{
  "design": {
    "shape": {
       "eye": "teardrop"
    }
  }
}
```

```bash
.build/release/qrcodegen --style-template-file qrtemplate.json  -t "QRCode on the clipboard" --output-file "fish.png" 1024
```

**Comment by dagronf** [comment]
@TakNePoidet hey mate, you can create a template file by saving a `QRCode.Document` to a file using the `.jsonData()`. (Unfortunately) there's no way other than code to create one.

There's currently no way to create a template file directly from the command line, however I realise that it makes sense to be able to use the command line to generate a template.  I'll add it.

**Comment by dagronf** [comment]
Hey mate - I've just pushed a new version (20.1.0) which includes the ability to generate a style template from the command line. 

You can export your QR code to JSON format eg.

`.build/debug/qrcodegen -e teardrop -t "QRCode on the clipboard" 512 --output-format json > template.json`

You can then use this as the style template for other code generations eg.

`.build/release/qrcodegen --style-template-file template.json  -t "This is my second QR Code" --output-file "fish.png" 1024`

Can you try this out an see how it works for you?

**Comment by TakNePoidet** [comment]
Everything is working, thank you very much!
