### ISSUE TITLE
 Multiple commands produce '/xxx/PrivacyInfo.xcprivacy'

### ISSUE THREAD

**Issue by Bob-GGB** [dagronf/QRCode#47]
pod 'DSF_QRCode', '~> 20.0.0'

I  pod it  and run my project .  but  error !

I already have the file PrivacyInfo.xcprivacy in my project。
 
Error: ’Multiple commands produce PrivacyInfo.xcprivacy’ (when using a third party library via cocoapods)

Solution: The problem seems to appear when using 3rd party cocoapods which include a PrivacyInfo.xcprivacy file.

The problem must be solved by the developer of the 3rd party lib by changing the podspec.
Change:

sp.resource = “Sources/Resources/PrivacyInfo.xcprivacy”

to

sp.resource_bundles = { “Podname” => “Sources/Resources/PrivacyInfo.xcprivacy” }

thanks

**Comment by dagronf** [comment]
Hey @Bob-GGB sorry about this oversight!

I've updated the cocoapods spec and pushed a new version (20.4.0) - can you please try this new version and let me know if it solves the issue for you?

**Comment by Bob-GGB** [comment]
Yes, I updated to V20.4.2, and now my problem has been solved. Thank you so much!!!
