### ISSUE TITLE
Can I customize the size of the "eye" and "pupil"?

### ISSUE THREAD

**Issue by Bob-GGB** [dagronf/QRCode#48]
Hello, I’m using your genius SDK, and it's really great. However, when customizing the "eye" and "pupil," I'm not sure if I can set their sizes. After fixing the additionalQuietZonePixels value is “0”, the "eye" and "pupil" appear very prominent (the size is a bit large). Therefore, I would like to adjust their sizes. Is it possible to customize their sizes?
thanks！

**Comment by dagronf** [comment]
Hey @Bob-GGB, the eye and pupil sizes are fixed by the QR code algorithm, so their sizes cannot be changed.

**Comment by Bob-GGB** [comment]
Thanks for your reply, it's a shame that you can't adjust the size!
