### ISSUE TITLE
Integrate this library to be used by watchOS with a React Native iOS Project

### ISSUE THREAD

**Issue by joaonew** [dagronf/QRCode#49]
Hello there,

I was able to implement this library in the native side with Swift and installing the package dependencies through Xcode, but when I try to run my iOS app (built with React Native), it does not recognize this library, which I believe I have to add to my Podfile to work.

By reading the issues here, I was able to get to this:

_target 'watchos Watch App' do
  platform :watchos, '7.0'
  pod 'DSF_QRCode'
end_

Which allow me to successfully run `pod install` in my iOS project, but when I try to run my iOS app (in order to run the watchOS app where this library is been used), I get this error:

![image](https://github.com/user-attachments/assets/c239989a-1f95-4fe9-850c-1dc3cc09012f)

Any ideas on why Im getting this?

**Comment by dagronf** [comment]
Hi @joaonew ,

It looks like you're linking the QRCode library multiple times against your app (the 4268 duplicate symbols).

I'm guessing that you've added QRCode via Cocoapods (ie. "pod 'DSF_QRCode'") in your comment.  The second via Xcode dependencies ("installing the package dependencies through Xcode").  You should only use a single method for integrating QRCode into your app.

If you're already using Cocoapods to get React Native, then I'd suggest using Cocoapods _only_ for installing QRCode.

Hope this helps.

**Comment by dagronf** [comment]
I just threw together a very simple watchos app using cocoapods.  It's using SwiftUI, but the same concept applies to React Native. Might give you some more insight into your own app.

The big note here is that QRCode is included via Cocoapods _only_.  No Xcode package dependencies.

**Comment by joaonew** [comment]
Thank you. I've decided to delete and redo all the configuration for watchOS to try to get it to work, I will give a close look in the project you shared, appreciated.

**Comment by joaonew** [comment]
> I just threw together a very simple watchos app using cocoapods. It's using SwiftUI, but the same concept applies to React Native. Might give you some more insight into your own app.
> 
> The big note here is that QRCode is included via Cocoapods _only_. No Xcode package dependencies.
> 
> [qr49-cocoapods-watchos.zip](https://github.com/user-attachments/files/16666826/qr49-cocoapods-watchos.zip)

How did add this cocoapods to your project? Can you break it down for me since adding it only to Podfile did not work for me.

**Comment by dagronf** [comment]
@joaonew Are you using Cocoapods for the rest of your app components (like React Native etc)?

**Comment by dagronf** [comment]
Just adding the podfile isn't sufficient, you'll need to also run `pod install` from within your project directory (in the terminal app). Have a look at the 'Getting Started' section in [the cocoapods documentation](https://cocoapods.org).  

Are you planning to use Cocoapods for all your other dependencies, like React Native etc?

**Comment by joaonew** [comment]
I did ran `pod install` after adding the pod 'DSF_QRCode' in my Podfile, I was wondering if you ran any other commands like yarn add ... because I noticed in your Podfile you had the pod 'DSF_QRCode' under your main app target as well.

I strip all the new communication code from my iOS app (to talk to the watch) but this QRCode lib apparently doesn't let me run my iOS app in Xcode anymore.

For now I can only run pod install without errors if I run `USE_FRAMEWORKS=static bundle exec pod install`, and even tho pod install is successful, when I run my iOS app in Xcode (already with the watchOS linked to it), I get:

![image](https://github.com/user-attachments/assets/465ac926-45b0-48be-8ef8-8c252581a531)

Any sugestions?

**Comment by dagronf** [comment]
The Sandbox error is related to an Xcode setting -- you need to set [`ENABLE_USER_SCRIPT_SANDBOXING` to 'No'](https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w)

This is a common issue with Cocoapods and Xcode versions > 12.

**Comment by dagronf** [comment]
Note that the attached demo app does NOT use React Native AT ALL.  I've never used React Native myself so I have no understanding about the requirements of including a platform-specific component into a Reach Native app.

**Comment by joaonew** [comment]
Thank you, that fixed the sandbox error.

Looks like they are never finished tho lol

![image](https://github.com/user-attachments/assets/941f056d-a7a6-442f-90bd-fa269769c754)

> Note that the attached demo app does NOT use React Native AT ALL. I've never used React Native myself so I have no understanding about the requirements of including a platform-specific component into a Reach Native app.

No worries, you helped a lot with your support!
