### ISSUE TITLE
Hello, can I suggest you support QR code decoration? As shown in the picture

### ISSUE THREAD

**Issue by Bob-GGB** [dagronf/QRCode#50]
the frame style link: https://www.qr-code-generator.com/
As shown in this picture：
![image](https://github.com/user-attachments/assets/d9b9810a-a2ca-4c55-bbcf-cd71612eba83)

**Comment by dagronf** [comment]
Moved to a [discussion thread](https://github.com/dagronf/QRCode/discussions/51) instead of an issue.
