### ISSUE TITLE
RoundedRect EyeShape (and PupilShape) with custom corner radius

### ISSUE THREAD

**Issue by matthew-dubois** [dagronf/QRCode#59]
Hello,

First, the package is great-- thank you!

I'm aware the RoundedRect eye or pupil shape _doesn't_ support defining a custom corner radius, although the pixel shape _does_. I'm wondering if this is a decoding limitation, or if it's possible with a custom generator?

Thanks again.

**Comment by dagronf** [comment]
@matthew-dubois Hi! And thanks for the kind words -- glad to hear its been useful for you.

There is no technical limitation for this, either in this library or in the qr code spec.  Just remember that the more stylish the code the less readable it is.

Theres nothing to stop you from creating your own custom eye/pupil generators that define a customizable corner radius.  

Cheers and thanks once again!

**Comment by dagronf** [comment]
@matthew-dubois Hey mate,

I've just pushed 23.2.0 which includes a 'cornerRadiusFraction' on both the `QRCode.EyeShape.RoundedRect` and the `QRCode.PupilShape.RoundedRect`.

Let me know how you go.

Cheers!

**Comment by matthew-dubois** [comment]
Hello,

I just tried it, and it's exactly what I was looking for.

Again, thank you for the quick response and update!
