### ISSUE TITLE
Support CocoaPods 

### ISSUE THREAD

**Issue by noblakit01** [dagronf/QRCode#6]
Hi, this framework is really awesome and I really need it in Cocoapods. Do you have a plan moving to CocoaPods?

**Comment by dagronf** [comment]
Hey mate - thanks for your kind words! I haven’t planned to support cocoapods (I dont use it anymore for my own projects) but if you make the change yourself and submit a pull request I’ll happily merge it into the repo. My experience with cocoapods is limited at best so if you have experience it would be most welcome.

**Comment by dagronf** [comment]
v13 adds cocoapods support
