### ISSUE TITLE
XCFramework 

### ISSUE THREAD

**Issue by PineConeDer** [dagronf/QRCode#7]
Can God generate an xcframework? I tried to generate one, but when added to the project, an error will be reported. . .

**Comment by dagronf** [comment]
I've never created an xcframework before, so if you can give me any information on how you were attempting to create one can you please share it?

**Comment by dagronf** [comment]
Due to the lack of feedback, I'm moving this [to a discussion](https://github.com/dagronf/QRCode/discussions/9) instead
